archi:
    name: baseline
    classifier: resnet50
    loss: partialbce
dataset:
    name: pascalvoc
    path: /home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/
    train: trainval
    test: test
batch_size: 32
training:
    n_epochs: 20
    optimizer: sgd
    start_lr: 0.1
