archi:
    name: baseline
    weldon:
        weldon_k_plus: 0.1
        weldon_k_minus: 0.1
dataset:
    name: pascalvoc
    path: /share/DEEPLEARNING/datasets/pascalvoc/
batch_size: 16
training:
    n_epochs: 20