archi:
    name: baseline
    classifier: resnet50
    loss: bce
dataset:
    name: coco
    path: /home/caleml/datasets/mscoco/
    train: train
    test: val
    year: '2014'
relabel:
    active: true
    name: relabel_prior
    steps: 3
    prior: conditional
    prior_path: /home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/Annotations/prior_matrix2_trainval_partial_$PROP_1.json
image:
    img_size: 448
batch_size: 16
training:
    n_epochs: 20
    optimizer: sgd
    start_lr: 0.01
    skip_val: true