archi:
    name: baseline
    classifier: resnet50
    loss: partialbce
dataset:
    name: coco
    path: /share/DEEPLEARNING/datasets/mscoco/
    train: train
    test: val
batch_size: 32
training:
    n_epochs: 20
    optimizer: sgd
    start_lr: 0.1
