parent_config: frcnn_baseline
archi:
    name: frcnn_baseline
dataset:
    name: oid
    path: /local/DEEPLEARNING/oid/
    train: train
    test: val
    nb_classes: 501
image:
    resize_mode: square
    img_size: 448
    nb_channels: 3
    mean_pixel:
        - 123.7
        - 116.8
        - 103.9
batch_size: 8
test_batch_size: 8
training:
    nb_epoch: 300       # with 5000 * 8 images per epoch we need 1578816 / (5000*8) = 50 epoch to see every image (100 epoch = 2 'true' epochs)
    steps_per_epoch: 5000
    optimizer: sgd
    start_lr: 0.001
    lr_momentum: 0.9
    weight_decay: 0.0001
    skip_val: true
    validation_steps: 50
callback:
    val_cb: map