archi:
    name: baseline
    classifier: resnet101
    loss: bce
dataset:
    name: pascalvoc
    path: /home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/
    train: train
    test: val
image:
    img_size: 448
batch_size: 16
test_batch_size: all
training:
    n_epochs: 20
    optimizer: sgd
    start_lr: 0.01
    skip_val: true
callback:
    val_cb: map