archi:
    name: baseline
    classifier: resnet50
    loss: partialbce
dataset:
    name: pascalvoc
    path: /home/caleml/datasets/pascalvoc/
batch_size: 32
training:
    n_epochs: 30
    optimizer: sgd
    start_lr: 0.1
