archi:
    name: baseline
    classifier: resnet50
    loss: bce
dataset:
    name: pascalvoc
    path: /home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/
    train: trainval
    test: test
relabel:
    active: true
    steps: 3
    prior: conditional
    prior_path: /home/caleml/datasets/pascalvoc/VOCdevkit/VOC2007/Annotations/prior_matrix_trainval_partial_100_1.json
image:
    img_size: 448
batch_size: 16
training:
    n_epochs: 1
    optimizer: sgd
    start_lr: 0.01